/**
 * Built-in demo word sets — available to every player (logged in or guest).
 * Keep definitions in the same language as classroom glossaries (EN term = PL gloss).
 */
(typeof window !== 'undefined' ? window : globalThis).LINGOSPARK_DEMO_SETS = [
  {
    id: 'matura-czlowiek',
    name: 'Matura podstawowa - Człowiek',
    description: 'Matura podstawowa — unit Człowiek (appearance, personality, clothes)',
    items: [
      { term: 'agreeable', definition: 'przyjemny, zgodny, miły' },
      { term: 'amazed', definition: 'Zdziwiony' },
      { term: 'an only child', definition: 'jedynak/jedynaczka' },
      { term: 'angry', definition: 'Zły' },
      { term: 'anorak', definition: 'Kurtka przeciwdeszczowa' },
      { term: 'appear', definition: 'pojawiać się, ukazywać się' },
      { term: 'apperance', definition: 'wygląd' },
      { term: 'awful', definition: 'Okropny' },
      { term: 'bachelor', definition: 'Kawaler' },
      { term: 'bad-tempered', definition: 'W złym humorze' },
      { term: 'bald', definition: 'Łysy' },
      { term: 'beard', definition: 'Broda' },
      { term: 'behaviour', definition: 'Zachowanie' },
      { term: 'big-headed', definition: 'Zarozumiały' },
      { term: 'bored', definition: 'Znudzony' },
      { term: 'bossy', definition: 'Apodyktyczny' },
      { term: 'bra', definition: 'Stanik' },
      { term: 'busy', definition: 'zajęty' },
      { term: 'caring', definition: 'opiekuńczy' },
      { term: 'catwalk', definition: 'Wybieg dla modelek' },
      { term: 'checked', definition: 'w kratkę' },
      { term: 'clothing', definition: 'Ubranie' },
      { term: 'compliment', definition: 'chwalić, gratulować' },
      { term: 'confident', definition: 'Pewny siebie' },
      { term: 'couple', definition: 'Kilka' },
      { term: 'creative', definition: 'Twórczy' },
      { term: 'curly', definition: 'kręcone' },
      { term: 'denim', definition: 'Dżins (tkanina)' },
      { term: 'depressed', definition: 'W depresji' },
      { term: 'disappointed', definition: 'Rozczarowany' },
      { term: 'divorce', definition: 'Rozwód' },
      { term: 'dressed to kill', definition: 'ubrany wystrzałowo' },
      { term: 'dungarees', definition: 'Ogrodniczki' },
      { term: 'easygoing', definition: 'Na luzie' },
      { term: 'egoistic', definition: 'Egoistyczny' },
      { term: 'excited', definition: 'Podekscytowany' },
      { term: 'fascinated by', definition: 'zafascynowany czymś' },
      { term: 'fashionable', definition: 'Modny' },
      { term: 'feature', definition: 'Cecha' },
      { term: 'first born', definition: 'Pierworodny' },
      { term: 'freckles', definition: 'Piegi' },
      { term: 'frightened', definition: 'Wystraszony' },
      { term: 'fringe', definition: 'Grzywka' },
      { term: 'fulfilment', definition: 'Satysfakcja' },
      { term: 'funeral', definition: 'Pogrzeb' },
      { term: 'furious', definition: 'wściekły' },
      { term: 'gender', definition: 'płeć, rodzaj' },
      { term: 'generous', definition: 'Szczodry' },
      { term: 'good-looking', definition: 'Przystojny' },
      { term: 'grow', definition: 'rosnąć' },
      { term: 'handsome', definition: 'Przystojny' },
      { term: 'hard-working', definition: 'Pracowity' },
      { term: 'high-heeled', definition: 'Na wysokich obcasach' },
      { term: 'honest', definition: 'Uczciwy' },
      { term: 'hopeless', definition: 'Beznadziejny' },
      { term: 'horrible', definition: 'Okropny' },
      { term: 'humble', definition: 'Skromny' },
      { term: 'indecisive', definition: 'Niezdecydowany' },
      { term: 'lazy', definition: 'Leniwy' },
      { term: 'loud', definition: 'głośny' },
      { term: 'make-up', definition: 'makijaż' },
      { term: 'marital status', definition: 'Stan cywilny' },
      { term: 'master (degree)', definition: '(Tytuł) magistra' },
      { term: 'medium-height', definition: 'Średniego wzrostu' },
      { term: 'mess', definition: 'bałagan, nieporządek' },
      { term: 'messy', definition: 'Niechlujny' },
      { term: 'mood', definition: 'nastrój, humor' },
      { term: 'moustache', definition: 'wąsy' },
      { term: 'outfit', definition: 'ubiór, strój' },
      { term: 'overambitious', definition: 'Zbyt ambitny' },
      { term: 'overweight', definition: 'z nadwagą (mający nadwagę)' },
      { term: 'passive', definition: 'Pasywny' },
      { term: 'pastime', definition: 'Rozrywka' },
      { term: 'pattern', definition: 'wzór' },
      { term: 'plump', definition: 'Pulchny' },
      { term: 'ponytail', definition: 'kucyk, koński ogon' },
      { term: 'poor', definition: 'Biedny' },
      { term: 'proud', definition: 'Dumny' },
      { term: 'rebellious', definition: 'Buntowniczy' },
      { term: 'reliable', definition: 'Niezawodny' },
      { term: 'respect', definition: 'szanować' },
      { term: 'revenge', definition: 'Zemsta' },
      { term: 'rude', definition: 'Nieuprzejmy' },
      { term: 'scar', definition: 'Blizna' },
      { term: 'scared', definition: 'Przestraszony' },
      { term: 'self-centred', definition: 'Samolubny' },
      { term: 'selfish', definition: 'Samolubny' },
      { term: 'shape', definition: 'kształt' },
      { term: 'shy', definition: 'nieśmiały' },
      { term: 'shocked', definition: 'Zszokowany' },
      { term: 'silk', definition: 'Jedwab' },
      { term: 'silly', definition: 'niemądry, głupkowaty' },
      { term: 'single', definition: 'Kawaler/panna' },
      { term: 'size', definition: 'Rozmiar' },
      { term: 'skill', definition: 'umiejętność' },
      { term: 'skinny', definition: 'Chudy' },
      { term: 'sleepy', definition: 'śpiący' },
      { term: 'smart', definition: 'Elegancki' },
      { term: 'social life', definition: 'Życie towarzyskie' },
      { term: 'stubborn', definition: 'Uparty' },
    ],
  },
  {
    id: 'matura-rozszerzona-czlowiek',
    name: 'Matura rozszerzona - Człowiek',
    description: 'Matura rozszerzona — unit Człowiek (identity, appearance, clothes, body language)',
    items: [
      { term: 'date of birth', definition: 'data urodzenia' },
      { term: 'citizenship', definition: 'obywatelstwo' },
      { term: 'sex', definition: 'płeć' },
      { term: 'first name', definition: 'imię' },
      { term: 'family name', definition: 'nazwisko' },
      { term: 'male', definition: 'płci męskiej' },
      { term: 'female', definition: 'płeć żeńska' },
      { term: 'marital status', definition: 'stan cywilny' },
      { term: 'middle name', definition: 'drugie imię' },
      { term: 'occupation', definition: 'zawód' },
      { term: 'ethnic group', definition: 'grupa etniczna' },
      { term: 'spouse', definition: 'współmałżonek' },
      { term: 'muscular', definition: 'muskularny' },
      { term: 'obese', definition: 'otyły' },
      { term: 'overweight', definition: 'z nadwagą' },
      { term: 'plump', definition: 'pulchny' },
      { term: 'skinny', definition: 'chudy' },
      { term: 'slim', definition: 'szczupły' },
      { term: 'stocky', definition: 'krępy' },
      { term: 'curly', definition: 'kręcone' },
      { term: 'fringe', definition: 'grzywka' },
      { term: 'frizzy', definition: 'kędzierzawe' },
      { term: 'highlights', definition: 'pasemka' },
      { term: 'plait', definition: 'warkocz' },
      { term: 'ponytail', definition: 'kucyk' },
      { term: 'in a bun', definition: 'w kok' },
      { term: 'dimple', definition: 'dołek' },
      { term: 'freckles', definition: 'piegi' },
      { term: 'beauty spot', definition: 'pieprzyk' },
      { term: 'piercing', definition: 'kolczyk' },
      { term: 'scar', definition: 'blizna' },
      { term: 'tattoo', definition: 'tatuaż' },
      { term: 'wrinkles', definition: 'zmarszczki' },
      { term: 'cape', definition: 'peleryna' },
      { term: 'cape cardigan', definition: 'rozpinany sweter' },
      { term: 'dressing gown', definition: 'szlafrok' },
      { term: 'hoodie', definition: 'bluza z kapturem' },
      { term: 'jersey', definition: 'sweter' },
      { term: 'sleeve', definition: 'rękaw' },
      { term: 'sweatshirt', definition: 'bluza' },
      { term: 'bracelet', definition: 'bransoletka' },
      { term: 'high heels', definition: 'buty na wysokim obcasie' },
      { term: 'motorcycle boots', definition: 'buty motocyklowe' },
      { term: 'necklace', definition: 'naszyjnik' },
      { term: 'scarf', definition: 'szalik' },
      { term: 'slippers', definition: 'kapcie' },
      { term: 'tie', definition: 'krawat' },
      { term: 'fold', definition: 'złożyć' },
      { term: 'shrink', definition: 'skurczyć się' },
      { term: 'stretch', definition: 'rozciągać się' },
      { term: 'undo the buttons', definition: 'rozpiąć guziki' },
      { term: 'baggy', definition: 'workowaty' },
      { term: 'casual', definition: 'nieformalny' },
      { term: 'creased', definition: 'wygnieciony' },
      { term: 'faded', definition: 'wypłowiały' },
      { term: 'feminine', definition: 'kobiecy' },
      { term: 'floaty', definition: 'zwiewny' },
      { term: 'floral', definition: 'w kwiaty' },
      { term: 'flowy', definition: 'spływający swobodnie' },
      { term: 'loose', definition: 'luźny' },
      { term: 'ripped', definition: 'podarty' },
      { term: 'scruffy', definition: 'niechlujny' },
      { term: 'shabby', definition: 'zaniedbany' },
      { term: 'sleeveless', definition: 'bez rękawów' },
      { term: 'elegant', definition: 'elegancki' },
      { term: 'stretchy', definition: 'rozciągliwy' },
      { term: 'striped', definition: 'w paski' },
      { term: 'stylish', definition: 'stylowy' },
      { term: 'tight', definition: 'ciasny' },
      { term: 'trendy', definition: 'modny' },
      { term: 'unique', definition: 'unikalny' },
      { term: 'vintage', definition: 'staromodny' },
      { term: 'blend into the crowd', definition: 'wmieszać się w tłum' },
      { term: 'conform to a style', definition: 'dopasować się do stylu' },
      { term: "express sb's individuality", definition: 'być wyrazem czyjejś indywidualności' },
      { term: 'switch allegiance', definition: 'zmienić przynależność' },
      { term: 'glance', definition: 'rzucić okiem' },
      { term: 'glare', definition: 'wpatrywać się ze złością' },
      { term: 'glimpse', definition: 'spojrzeć przelotnie' },
      { term: 'inspect', definition: 'zlustrować' },
      { term: 'peek', definition: 'zerkać' },
      { term: 'peer', definition: 'przyglądać się' },
      { term: 'stare', definition: 'gapić się' },
      { term: 'watch', definition: 'obserwować' },
      { term: 'hiss', definition: 'syczeć' },
      { term: 'moan', definition: 'jęczeć' },
      { term: 'mumble', definition: 'mamrotać' },
      { term: 'shout', definition: 'krzyczeć' },
      { term: 'stutter', definition: 'jąkać się' },
      { term: 'whisper', definition: 'szeptać' },
      { term: 'yell', definition: 'wrzeszczeć' },
      { term: 'bang your fist', definition: 'uderzyć pięścią' },
      { term: 'cross your legs', definition: 'skrzyżować nogi' },
      { term: 'fold your arms', definition: 'skrzyżować ramiona' },
      { term: 'frown', definition: 'zmarszczyć brwi' },
      { term: 'gesture', definition: 'gest' },
      { term: 'hands on hips', definition: 'ręce na biodrach' },
      { term: 'have your elbows on the table', definition: 'opierać się łokciami o stół' },
      { term: 'hide your face in your hands', definition: 'ukryć twarz w dłoniach' },
      { term: 'hug', definition: 'objąć' },
    ],
  },
];
