/**
 * Built-in demo word sets — available to every player (logged in or guest).
 * Keep definitions in the same language as classroom glossaries (EN term = PL gloss).
 */
(typeof window !== 'undefined' ? window : globalThis).LINGOSPARK_DEMO_SETS = [
  {
    id: 'personality',
    name: 'Personality',
    description: 'Character traits, family & relationships — ready-made demo set',
    items: [
      { term: 'Abandon', definition: 'Porzucić' },
      { term: 'Acquaintance', definition: 'Znajomy' },
      { term: "Act in someone's best interests", definition: 'Działać w czyimś najlepszym interesie' },
      { term: 'The aged', definition: 'Osoby starsze' },
      { term: 'Aggressive', definition: 'Agresywny' },
      { term: 'Alien', definition: 'Cudzoziemiec (formalnie) / Obcy' },
      { term: 'Altruism', definition: 'Altruizm' },
      { term: 'Altruistic', definition: 'Altruistyczny' },
      { term: 'Ancestors', definition: 'Przodkowie' },
      { term: 'Ancient', definition: 'Starożytny' },
      { term: 'Apathetic', definition: 'Apatyczny' },
      { term: 'Astute', definition: 'bystry, przenikliwy' },
      { term: 'Attentive', definition: 'Uważny' },
      { term: 'Best man', definition: 'Świadek' },
      { term: 'Betrothed / Fiancée', definition: 'Narzeczony / Narzeczona' },
      { term: 'Bloke / Chap / Lad', definition: 'Facet / Gość / Chłopak' },
      { term: 'Born leader', definition: 'Urodzony przywódca' },
      { term: 'bridegroom/groom', definition: 'Pan młody' },
      { term: 'Broad-minded', definition: 'tolerancyjny, o otwartym umyśle' },
      { term: 'Chauvinistic', definition: 'Szowinistyczny' },
      { term: 'Cheerful', definition: 'Radosny' },
      { term: 'A close call', definition: 'O mały włos' },
      { term: 'Close to tears', definition: 'Bliski łez' },
      { term: 'Colleague', definition: 'Kolega z pracy' },
      { term: 'Commitment', definition: 'Zobowiązanie' },
      { term: 'Conscientious', definition: 'Sumienny' },
      { term: 'Contemporaries', definition: 'rówieśnicy, współcześni' },
      { term: 'Cunning', definition: 'Przebiegły' },
      { term: 'Descendants', definition: 'Potomkowie' },
      { term: 'Devoted', definition: 'Oddany' },
      { term: 'Diligence', definition: 'Pilność' },
      { term: 'Diligent', definition: 'Pilny' },
      { term: 'Distrustful', definition: 'Nieufny' },
      { term: 'Dogged', definition: 'Zacięty' },
      { term: 'Domineering', definition: 'Apodyktyczny' },
      { term: 'Downfall', definition: 'Upadek' },
      { term: 'Down-to-earth', definition: 'Twardo stąpający po ziemi' },
      { term: 'Elder', definition: 'Starszy (rangą/wiekiem)' },
      { term: 'Eligible bachelor', definition: 'kawaler do wzięcia' },
      { term: 'Extended family', definition: 'rodzina wielopokoleniowa, dalsza rodzina' },
      { term: 'Extrovert', definition: 'Ekstrawertyk' },
      { term: 'Fault-finder', definition: 'Krytykant' },
      { term: 'Flashy dresser', definition: 'Szpaner (w ubiorze)' },
      { term: 'Flexible', definition: 'Elastyczny' },
      { term: "Follow in someone's footsteps", definition: 'Iść w czyjeś ślady' },
      { term: 'Fun-loving', definition: 'Lubiący zabawę' },
      { term: 'Gallant', definition: 'Szarmancki' },
      { term: 'Gallantry', definition: 'Szarmanckość' },
      { term: 'Generous', definition: 'Hojny' },
      { term: 'Get carried away', definition: 'Dać się ponieść' },
      { term: 'Gifted', definition: 'Utalentowany' },
      { term: 'Give and take', definition: 'Kompromis / Wzajemne ustępstwa' },
      { term: 'Godfather', definition: 'Ojciec chrzestny' },
      { term: 'Go steady with someone', definition: 'Chodzić z kimś na stałe' },
      { term: 'Go through a bad patch', definition: 'Przechodzić trudny okres' },
      { term: 'Hit it off', definition: 'Polubić się od razu' },
      { term: 'Household', definition: 'Gospodarstwo domowe' },
      { term: 'Humiliate', definition: 'Upokarzać' },
      { term: 'Immoderate', definition: 'Nieumiarkowany' },
      { term: 'Industrious', definition: 'Pracowity' },
      { term: 'Insensitive', definition: 'Niewrażliwy' },
      { term: 'Intuitive', definition: 'Intuicyjny' },
      { term: 'Juvenile', definition: 'Młodociany' },
      { term: 'Lazy', definition: 'Leniwy' },
      { term: 'Live up to expectations', definition: 'Sprostać oczekiwaniom' },
      { term: 'Lowbrow', definition: 'Niewybredny (o guście)' },
      { term: 'Magnetic personality', definition: 'Magnetyczna osobowość' },
      { term: 'Make it up', definition: 'Pogodzić się' },
      { term: 'Methodical', definition: 'metodyczny, systematyczny' },
      { term: 'Morose', definition: 'Ponury' },
      { term: 'Mulish', definition: 'Uparty jak osioł' },
      { term: 'Naïve', definition: 'Naiwny' },
      { term: 'Nearest and dearest', definition: 'Najbliżsi (rodzina)' },
      { term: 'Neglect', definition: 'Zaniedbywać' },
      { term: 'Newlyweds', definition: 'Nowożeńcy' },
      { term: 'Nuclear family', definition: 'najbliższa rodzina (rodzice i dzieci)' },
      { term: 'Obliging', definition: 'Uczynny' },
      { term: 'Only child', definition: 'Jedynak' },
      { term: 'Opportunistic', definition: 'oportunistyczny, wykorzystuje sytuacje na swoją korzyść' },
      { term: 'Outcasts', definition: 'Wyrzutkowie' },
      { term: 'Outsider', definition: 'osoba z zewnątrz' },
      { term: 'Over-protective parents', definition: 'Nadopiekuńczy rodzice' },
      { term: 'Parsimonious', definition: 'Przesadnie oszczędny' },
      { term: 'Parsimony', definition: 'Skąpstwo' },
      { term: 'Pithy', definition: 'zwięzły, treściwy' },
      { term: 'Placid', definition: 'Łagodny' },
      { term: 'Placidity', definition: 'Łagodność' },
      { term: 'Plagued by worry', definition: 'Dręczony zmartwieniami' },
      { term: 'Pluck up courage', definition: 'Zdobyć się na odwagę' },
      { term: 'Predecessors', definition: 'Poprzednicy' },
      { term: 'Prejudiced', definition: 'Uprzedzony' },
      { term: 'Procrastinate', definition: 'Zwlekać' },
      { term: 'Pushy', definition: 'Natrętny' },
      { term: 'Put pressure on', definition: 'Wywierać presję na' },
      { term: 'Quarrel', definition: 'Kłócić się' },
      { term: 'Quick-tempered', definition: 'Porywczy' },
      { term: 'Rebel against upbringing', definition: 'Buntować się przeciwko wychowaniu' },
      { term: 'Relation / Relative', definition: 'Krewny' },
      { term: 'Resolute', definition: 'zdecydowany, stanowczy, niezachwiany' },
      { term: 'Sagacious', definition: 'mądry, roztropny' },
      { term: 'Sagacity', definition: 'mądrość, przenikliwość' },
      { term: 'Scold', definition: 'Karcić' },
      { term: 'Selfish', definition: 'Samolubny' },
      { term: 'Self-seeking', definition: 'Interesowny' },
      { term: 'Shake confidence', definition: 'Zachwiać pewnością' },
      { term: 'Shake with rage', definition: 'Trząść się ze wściekłości' },
      { term: 'Sharp-tongued', definition: 'Uszczypliwy' },
      { term: 'Sheltered upbringing', definition: 'Wychowanie pod kloszem' },
      { term: 'Shrewd', definition: 'sprytny, przebiegły' },
      { term: 'Solitary', definition: 'Samotniczy' },
      { term: 'Spoilt child', definition: 'Rozpieszczone dziecko' },
      { term: 'Steady decline', definition: 'Stały spadek' },
      { term: 'Stingy', definition: 'Skąpy' },
      { term: 'Stranger', definition: 'Nieznajomy' },
      { term: "Strike out on one's own", definition: 'Usamodzielnić się' },
      { term: 'Stubborn', definition: 'Uparty' },
      { term: 'Sullen', definition: 'Mrukliwy' },
      { term: 'Superficial', definition: 'Powierzchowny' },
      { term: 'Tactless', definition: 'Nietaktowny' },
      { term: 'Take offence', definition: 'Obrazić się' },
      { term: 'Terse', definition: 'Szorstki (w mowie)' },
      { term: 'Thick-skinned', definition: 'Gruboskórny' },
      { term: 'Thrifty / Frugal', definition: 'Oszczędny' },
      { term: 'Toddler', definition: 'brzdąc, szkrab, dziecko uczące się chodzić' },
      { term: 'Trial separation', definition: 'Separacja próbna' },
      { term: 'Unbearably close', definition: 'Nieznośnie duszno' },
      { term: 'Unhelpful', definition: 'Nieskory do pomocy' },
      { term: 'Unprincipled', definition: 'pozbawiony skrupułów' },
      { term: 'Unscrupulous', definition: 'Bez skrupułów' },
      { term: 'Unstinting', definition: 'Szczodry' },
      { term: 'Unsystematic', definition: 'Niesystematyczny' },
      { term: 'Walk someone down the aisle', definition: 'Poprowadzić kogoś do ołtarza' },
      { term: 'Witty', definition: 'Dowcipny' },
      { term: 'Work-obsessed', definition: 'pochłonięty pracą' },
    ],
  },
];
