window.LS_SHOP = {
    email: 'karolsenk@gmail.com',
    bmcShop: 'https://buymeacoffee.com/lingospark/extras',
    // Optional on a product: buyUrl: 'https://buymeacoffee.com/lingospark/e/EXTRA_ID'
    introTitle: 'Sklep dla nauczycieli',
    intro:
        'Gotowe paczki słówek na egzamin ósmoklasisty i maturę podstawową. Wklejasz listę do darmowych gier LingoSpark (bomba, fiszki, aukcja, live quiz) i od razu grasz. W ZIP-ie są też karty do druku i klucz. Płatność w sklepie Buy Me a Coffee — po zakupie plik przychodzi na maila. Licencja: jedna osoba, jedna klasa.',
    products: [
        {
            id: 'ls-8-complete',
            sku: 'LS-8-COMPLETE',
            featured: true,
            exam: 'Egzamin ósmoklasisty',
            title: 'Komplet 14 działów CKE',
            image: 'shop/previews/ls-8-complete.svg',
            terms: 1755,
            pricePln: 179,
            priceUsd: 49.5,
            description:
                'Pełny komplet 14 działów z informatora CKE — łącznie ponad 1700 haseł na poziomie A2–B1, bez powtórek między modułami. Każdy dział ma listy do wklejenia w gry, karty pracy i klucz. Taniej niż kupno wszystkich paczek osobno.',
        },
        {
            id: 'osmoklasista-czlowiek',
            sku: 'LS-8-PERSON',
            exam: 'Egzamin ósmoklasisty',
            title: 'Człowiek',
            image: 'shop/previews/osmoklasista-czlowiek.svg',
            terms: 124,
            pricePln: 22,
            priceUsd: 5.5,
            description:
                'Dział Człowiek: wygląd, cechy charakteru, ubrania i emocje. Około 120 autentycznych haseł na ósmoklasistę — wklejasz do gier LingoSpark i dostajesz karty z kluczem na lekcję.',
        },
        {
            id: 'osmoklasista-dom',
            sku: 'LS-8-HOME',
            exam: 'Egzamin ósmoklasisty',
            title: 'Miejsce zamieszkania',
            image: 'shop/previews/osmoklasista-dom.svg',
            terms: 119,
            pricePln: 22,
            priceUsd: 5.5,
            description:
                'Typy domów, pomieszczenia, meble i okolica. Paczka na dział Miejsce zamieszkania: listy PL/EN do gier oraz karty matching, luk i mini-quiz.',
        },
        {
            id: 'osmoklasista-edukacja',
            sku: 'LS-8-SCHOOL',
            exam: 'Egzamin ósmoklasisty',
            title: 'Edukacja',
            image: 'shop/previews/osmoklasista-edukacja.svg',
            terms: 120,
            pricePln: 22,
            priceUsd: 5.5,
            description:
                'Szkoła, przedmioty, oceny, egzaminy i życie klasy. Hasła gotowe do Bomb Defusal, fiszek i Live Quiz — plus materiały do druku.',
        },
        {
            id: 'osmoklasista-praca',
            sku: 'LS-8-WORK',
            exam: 'Egzamin ósmoklasisty',
            title: 'Praca',
            image: 'shop/previews/osmoklasista-praca.svg',
            terms: 121,
            pricePln: 22,
            priceUsd: 5.5,
            description:
                'Zawody, etat, rozmowa kwalifikacyjna i pierwsze pieniądze — prostsze niż matura, ale pełny dział CKE. Idealne pod 45-minutowe lekcje z grą.',
        },
        {
            id: 'osmoklasista-zycie-prywatne',
            sku: 'LS-8-LIFE',
            exam: 'Egzamin ósmoklasisty',
            title: 'Życie prywatne',
            image: 'shop/previews/osmoklasista-zycie-prywatne.svg',
            terms: 122,
            pricePln: 22,
            priceUsd: 5.5,
            description:
                'Rodzina, znajomi, rutyna dnia i czas wolny. Lista na dział Życie prywatne z przykładami w zdaniach i kartami do pracy w parach.',
        },
        {
            id: 'osmoklasista-zywienie',
            sku: 'LS-8-FOOD',
            exam: 'Egzamin ósmoklasisty',
            title: 'Żywienie',
            image: 'shop/previews/osmoklasista-zywienie.svg',
            terms: 131,
            pricePln: 22,
            priceUsd: 5.5,
            description:
                'Posiłki, smaki, gotowanie i jedzenie na mieście. Największa paczka E8 — wklejasz pełną listę albo zestawy po 20 haseł na lekcję.',
        },
        {
            id: 'osmoklasista-zakupy',
            sku: 'LS-8-SHOP',
            exam: 'Egzamin ósmoklasisty',
            title: 'Zakupy i usługi',
            image: 'shop/previews/osmoklasista-zakupy.svg',
            terms: 123,
            pricePln: 22,
            priceUsd: 5.5,
            description:
                'Sklepy, płatność, reklamacja, poczta i usługi. Hasła, których uczniowie potrzebują w dialogach i na egzaminie ustnym.',
        },
        {
            id: 'osmoklasista-podroze',
            sku: 'LS-8-TRAVEL',
            exam: 'Egzamin ósmoklasisty',
            title: 'Podróże',
            image: 'shop/previews/osmoklasista-podroze.svg',
            terms: 130,
            pricePln: 22,
            priceUsd: 5.5,
            description:
                'Lotnisko, dworzec, hotel, zwiedzanie i pytanie o drogę. Dział Podróżowanie i turystyka z listami do gier i kartami na lekcję.',
        },
        {
            id: 'osmoklasista-kultura',
            sku: 'LS-8-CULTURE',
            exam: 'Egzamin ósmoklasisty',
            title: 'Kultura',
            image: 'shop/previews/osmoklasista-kultura.svg',
            terms: 130,
            pricePln: 22,
            priceUsd: 5.5,
            description:
                'Film, książka, muzyka, teatr i tradycje. Paczka na dział Kultura — od kina po folklor — pod fiszki, bombę i quiz na żywo.',
        },
        {
            id: 'osmoklasista-sport',
            sku: 'LS-8-SPORT',
            exam: 'Egzamin ósmoklasisty',
            title: 'Sport',
            image: 'shop/previews/osmoklasista-sport.svg',
            terms: 128,
            pricePln: 22,
            priceUsd: 5.5,
            description:
                'Dyscypliny, sprzęt, mecz i kibice. Lista na dział Sport z zestawami po 20 haseł — w sam raz na lekcję WF-owo-angielską albo powtórkę.',
        },
        {
            id: 'osmoklasista-zdrowie',
            sku: 'LS-8-HEALTH',
            exam: 'Egzamin ósmoklasisty',
            title: 'Zdrowie',
            image: 'shop/previews/osmoklasista-zdrowie.svg',
            terms: 127,
            pricePln: 22,
            priceUsd: 5.5,
            description:
                'Objawy, wizyta u lekarza, zdrowy styl życia i pierwsza pomoc. Poziom ósmoklasisty — nie kopia listy maturalnej ze strony.',
        },
        {
            id: 'osmoklasista-nauka-technika',
            sku: 'LS-8-TECH',
            exam: 'Egzamin ósmoklasisty',
            title: 'Nauka i technika',
            image: 'shop/previews/osmoklasista-nauka-technika.svg',
            terms: 127,
            pricePln: 22,
            priceUsd: 5.5,
            description:
                'Komputer, internet, urządzenia i proste słownictwo naukowe. Dział Nauka i technika gotowy do wklejenia w gry LingoSpark.',
        },
        {
            id: 'osmoklasista-przyroda',
            sku: 'LS-8-NATURE',
            exam: 'Egzamin ósmoklasisty',
            title: 'Świat przyrody',
            image: 'shop/previews/osmoklasista-przyroda.svg',
            terms: 126,
            pricePln: 22,
            priceUsd: 5.5,
            description:
                'Pogoda, krajobraz, zwierzęta i ekologia. Paczka na Świat przyrody z kartami do druku i listami PL oraz EN.',
        },
        {
            id: 'osmoklasista-zycie-spoleczne',
            sku: 'LS-8-SOCIAL',
            exam: 'Egzamin ósmoklasisty',
            title: 'Życie społeczne',
            image: 'shop/previews/osmoklasista-zycie-spoleczne.svg',
            terms: 127,
            pricePln: 22,
            priceUsd: 5.5,
            description:
                'Społeczność, prawo, wybory, wolontariat i dobre maniery. Dział Życie społeczne pod dialogi, gry i karty pracy.',
        },
        {
            id: 'matura-pp-praca',
            sku: 'LS-MAT-WORK',
            exam: 'Matura podstawowa',
            title: 'Matura PP: Praca',
            image: 'shop/previews/matura-pp-praca.svg',
            terms: 36,
            pricePln: 17,
            priceUsd: 4.25,
            description:
                '36 haseł z działu Praca na maturę podstawową: CV, etat, nadgodziny, zwolnienie. Dwie lekcje po 45 minut — listy do gier i karty z kluczem.',
        },
        {
            id: 'matura-pp-zdrowie',
            sku: 'LS-MAT-HEALTH',
            exam: 'Matura podstawowa',
            title: 'Matura PP: Zdrowie',
            image: 'shop/previews/matura-pp-zdrowie.svg',
            terms: 36,
            pricePln: 17,
            priceUsd: 4.25,
            description:
                'Objawy, wizyta u lekarza i leczenie na poziomie matury podstawowej. 36 haseł, zestawy A i B, karty do druku. To nie jest lista E8.',
        },
    ],
};
