window.LS_SHOP = {
    email: 'karolsenk@gmail.com',
    bmcShop: 'https://buymeacoffee.com/lingospark/extras',
    categories: [
        { id: 'all', pl: 'Wszystkie', en: 'All' },
        { id: 'planery', pl: 'Planery', en: 'Planners' },
        { id: 'fiszki', pl: 'Fiszki', en: 'Flashcards' },
        { id: 'ebooki', pl: 'Ebooki', en: 'Ebooks' },
        { id: 'karty-pracy', pl: 'Karty pracy', en: 'Worksheets' },
        { id: 'prezentacje', pl: 'Prezentacje', en: 'Presentations' },
    ],
    i18n: {
        pl: {
            pageTitle: 'Sklep — materiały dla nauczyciela i ucznia | LingoSpark',
            introTitle: 'Sklep dla nauczyciela i ucznia',
            intro:
                'Gotowe materiały na egzamin ósmoklasisty i maturę podstawową: planery, fiszki, karty pracy i listy słówek do darmowych gier LingoSpark. Płatność w sklepie Buy Me a Coffee — po zakupie plik przychodzi na maila. Licencja: jedna osoba, jedna klasa.',
            openShop: 'Otwórz sklep',
            questions: 'Pytania',
            browseCategories: 'Kategorie',
            examLevel: 'Poziom',
            examAll: 'Wszystkie poziomy',
            examStudyPlan: 'Plan nauki',
            examE8: 'Ósmoklasista',
            examMatura: 'Matura PP',
            buy: 'Kup',
            terms: 'haseł',
            studyPlanMeta: 'PDF · ok. 90 stron',
            studyPlanKicker: 'Plan nauki',
            previewHint: (n) => `Przewiń podgląd · ${n} strony z PDF`,
            emptyCategory: 'W tej kategorii nie ma jeszcze produktów. Sprawdź inne kategorie lub wróć do „Wszystkie”.',
            note:
                'Gry słownikowe na LingoSpark zostają darmowe. Paczki to listy + materiały do druku — kupujesz je w sklepie <a href="https://buymeacoffee.com/lingospark/extras" target="_blank" rel="noopener">Buy Me a Coffee / extras</a>. Writing Suite (tydzień / miesiąc / rok) też jest tam. Po zakupie ZIP przychodzi na maila z zamówienia.',
            langLabel: 'Język',
        },
        en: {
            pageTitle: 'Shop — materials for teachers and students | LingoSpark',
            introTitle: 'Shop for teachers and students',
            intro:
                'Ready-made materials for the Grade 8 exam and basic Matura: planners, flashcards, worksheets, and word lists for free LingoSpark games. Pay in the Buy Me a Coffee shop — files are delivered by email after purchase. Licence: one teacher, one class.',
            openShop: 'Open shop',
            questions: 'Questions',
            browseCategories: 'Categories',
            examLevel: 'Level',
            examAll: 'All levels',
            examStudyPlan: 'Study plan',
            examE8: 'Grade 8 exam',
            examMatura: 'Matura PP',
            buy: 'Buy',
            terms: 'terms',
            studyPlanMeta: 'PDF · approx. 90 pages',
            studyPlanKicker: 'Study plan',
            previewHint: (n) => `Scroll preview · ${n} pages from PDF`,
            emptyCategory: 'No products in this category yet. Try another category or go back to All.',
            note:
                'Vocab games on LingoSpark stay free. Packs are word lists plus printable materials — buy them in the <a href="https://buymeacoffee.com/lingospark/extras" target="_blank" rel="noopener">Buy Me a Coffee / extras</a> shop. Writing Suite (week / month / year) is there too. After purchase, the ZIP is sent to your order email.',
            langLabel: 'Language',
        },
    },
    products: [
        {
            id: 'e8-2027-study-plan',
            sku: 'LS-8-STUDY',
            featured: true,
            kind: 'study-plan',
            categories: ['planery'],
            exam: 'Egzamin ósmoklasisty',
            title: { pl: 'Plan nauki E8 2027', en: 'E8 2027 Study Plan' },
            image: 'shop/previews/e8-2027-study-plan.svg',
            previewPages: [
                'shop/previews/e8-study-plan/page-1.png',
                'shop/previews/e8-study-plan/page-2.png',
                'shop/previews/e8-study-plan/page-3.png',
                'shop/previews/e8-study-plan/page-4.png',
            ],
            terms: 1755,
            pricePln: 40,
            priceUsd: 10,
            description: {
                pl: 'Zeszyt PDF do druku: harmonogram, checklisty gramatyki, 14 działów CKE, mapy myśli i 1755 haseł. Dla ucznia ósmoklasisty.',
                en: 'Printable PDF workbook: schedule, grammar checklists, 14 CKE topics, mind maps, and 1755 terms. For Grade 8 students.',
            },
        },
        {
            sku: 'LS-8-COMPLETE',
            featured: true,
            categories: ['fiszki', 'karty-pracy'],
            exam: 'Egzamin ósmoklasisty',
            title: { pl: 'Komplet 14 działów CKE', en: 'Complete CKE 14 Topics Bundle' },
            image: 'shop/previews/ls-8-complete.svg',
            terms: 1755,
            pricePln: 99,
            priceUsd: 29,
            description: {
                pl: 'Wszystkie 14 działów CKE — ponad 1700 haseł, listy do gier i karty z kluczem.',
                en: 'All 14 CKE topics — over 1700 terms, game-ready lists, and printable cards with answer key.',
            },
        },
        {
            id: 'osmoklasista-czlowiek',
            sku: 'LS-8-PERSON',
            categories: ['fiszki', 'karty-pracy'],
            exam: 'Egzamin ósmoklasisty',
            title: { pl: 'Człowiek', en: 'People' },
            image: 'shop/previews/osmoklasista-czlowiek.svg',
            terms: 124,
            pricePln: 12,
            priceUsd: 3,
            description: {
                pl: 'Wygląd, cechy charakteru, ubrania i emocje.',
                en: 'Appearance, personality traits, clothes, and emotions.',
            },
        },
        {
            id: 'osmoklasista-dom',
            sku: 'LS-8-HOME',
            categories: ['fiszki', 'karty-pracy'],
            exam: 'Egzamin ósmoklasisty',
            title: { pl: 'Miejsce zamieszkania', en: 'Home and Living' },
            image: 'shop/previews/osmoklasista-dom.svg',
            terms: 119,
            pricePln: 12,
            priceUsd: 3,
            description: {
                pl: 'Typy domów, pomieszczenia, meble i okolica.',
                en: 'Types of homes, rooms, furniture, and the neighbourhood.',
            },
        },
        {
            id: 'osmoklasista-edukacja',
            sku: 'LS-8-SCHOOL',
            categories: ['fiszki', 'karty-pracy'],
            exam: 'Egzamin ósmoklasisty',
            title: { pl: 'Edukacja', en: 'Education' },
            image: 'shop/previews/osmoklasista-edukacja.svg',
            terms: 120,
            pricePln: 12,
            priceUsd: 3,
            description: {
                pl: 'Szkoła, przedmioty, oceny, egzaminy i życie klasy.',
                en: 'School, subjects, grades, exams, and classroom life.',
            },
        },
        {
            id: 'osmoklasista-praca',
            sku: 'LS-8-WORK',
            categories: ['fiszki', 'karty-pracy'],
            exam: 'Egzamin ósmoklasisty',
            title: { pl: 'Praca', en: 'Work' },
            image: 'shop/previews/osmoklasista-praca.svg',
            terms: 121,
            pricePln: 12,
            priceUsd: 3,
            description: {
                pl: 'Zawody, etat, rozmowa kwalifikacyjna i pierwsze pieniądze.',
                en: 'Jobs, employment, job interviews, and first earnings.',
            },
        },
        {
            id: 'osmoklasista-zycie-prywatne',
            sku: 'LS-8-LIFE',
            categories: ['fiszki', 'karty-pracy'],
            exam: 'Egzamin ósmoklasisty',
            title: { pl: 'Życie prywatne', en: 'Private Life' },
            image: 'shop/previews/osmoklasista-zycie-prywatne.svg',
            terms: 122,
            pricePln: 12,
            priceUsd: 3,
            description: {
                pl: 'Rodzina, znajomi, rutyna dnia i czas wolny.',
                en: 'Family, friends, daily routine, and free time.',
            },
        },
        {
            id: 'osmoklasista-zywienie',
            sku: 'LS-8-FOOD',
            categories: ['fiszki', 'karty-pracy'],
            exam: 'Egzamin ósmoklasisty',
            title: { pl: 'Żywienie', en: 'Food and Nutrition' },
            image: 'shop/previews/osmoklasista-zywienie.svg',
            terms: 131,
            pricePln: 12,
            priceUsd: 3,
            description: {
                pl: 'Posiłki, smaki, gotowanie i jedzenie na mieście.',
                en: 'Meals, flavours, cooking, and eating out.',
            },
        },
        {
            id: 'osmoklasista-zakupy',
            sku: 'LS-8-SHOP',
            categories: ['fiszki', 'karty-pracy'],
            exam: 'Egzamin ósmoklasisty',
            title: { pl: 'Zakupy i usługi', en: 'Shopping and Services' },
            image: 'shop/previews/osmoklasista-zakupy.svg',
            terms: 123,
            pricePln: 12,
            priceUsd: 3,
            description: {
                pl: 'Sklepy, płatność, reklamacja, poczta i usługi.',
                en: 'Shops, payment, complaints, post office, and services.',
            },
        },
        {
            id: 'osmoklasista-podroze',
            sku: 'LS-8-TRAVEL',
            categories: ['fiszki', 'karty-pracy'],
            exam: 'Egzamin ósmoklasisty',
            title: { pl: 'Podróże', en: 'Travel' },
            image: 'shop/previews/osmoklasista-podroze.svg',
            terms: 130,
            pricePln: 12,
            priceUsd: 3,
            description: {
                pl: 'Lotnisko, dworzec, hotel, zwiedzanie i pytanie o drogę.',
                en: 'Airport, station, hotel, sightseeing, and asking for directions.',
            },
        },
        {
            id: 'osmoklasista-kultura',
            sku: 'LS-8-CULTURE',
            categories: ['fiszki', 'karty-pracy'],
            exam: 'Egzamin ósmoklasisty',
            title: { pl: 'Kultura', en: 'Culture' },
            image: 'shop/previews/osmoklasista-kultura.svg',
            terms: 130,
            pricePln: 12,
            priceUsd: 3,
            description: {
                pl: 'Film, książka, muzyka, teatr i tradycje.',
                en: 'Film, books, music, theatre, and traditions.',
            },
        },
        {
            id: 'osmoklasista-sport',
            sku: 'LS-8-SPORT',
            categories: ['fiszki', 'karty-pracy'],
            exam: 'Egzamin ósmoklasisty',
            title: { pl: 'Sport', en: 'Sport' },
            image: 'shop/previews/osmoklasista-sport.svg',
            terms: 128,
            pricePln: 12,
            priceUsd: 3,
            description: {
                pl: 'Dyscypliny, sprzęt, mecz i kibice.',
                en: 'Sports, equipment, matches, and fans.',
            },
        },
        {
            id: 'osmoklasista-zdrowie',
            sku: 'LS-8-HEALTH',
            categories: ['fiszki', 'karty-pracy'],
            exam: 'Egzamin ósmoklasisty',
            title: { pl: 'Zdrowie', en: 'Health' },
            image: 'shop/previews/osmoklasista-zdrowie.svg',
            terms: 127,
            pricePln: 12,
            priceUsd: 3,
            description: {
                pl: 'Objawy, wizyta u lekarza, zdrowy styl życia i pierwsza pomoc.',
                en: 'Symptoms, doctor visits, healthy lifestyle, and first aid.',
            },
        },
        {
            id: 'osmoklasista-nauka-technika',
            sku: 'LS-8-TECH',
            categories: ['fiszki', 'karty-pracy'],
            exam: 'Egzamin ósmoklasisty',
            title: { pl: 'Nauka i technika', en: 'Science and Technology' },
            image: 'shop/previews/osmoklasista-nauka-technika.svg',
            terms: 127,
            pricePln: 12,
            priceUsd: 3,
            description: {
                pl: 'Komputer, internet, urządzenia i proste słownictwo naukowe.',
                en: 'Computers, the internet, devices, and basic science vocabulary.',
            },
        },
        {
            id: 'osmoklasista-przyroda',
            sku: 'LS-8-NATURE',
            categories: ['fiszki', 'karty-pracy'],
            exam: 'Egzamin ósmoklasisty',
            title: { pl: 'Świat przyrody', en: 'Nature' },
            image: 'shop/previews/osmoklasista-przyroda.svg',
            terms: 126,
            pricePln: 12,
            priceUsd: 3,
            description: {
                pl: 'Pogoda, krajobraz, zwierzęta i ekologia.',
                en: 'Weather, landscape, animals, and ecology.',
            },
        },
        {
            id: 'osmoklasista-zycie-spoleczne',
            sku: 'LS-8-SOCIAL',
            categories: ['fiszki', 'karty-pracy'],
            exam: 'Egzamin ósmoklasisty',
            title: { pl: 'Życie społeczne', en: 'Social Life' },
            image: 'shop/previews/osmoklasista-zycie-spoleczne.svg',
            terms: 127,
            pricePln: 12,
            priceUsd: 3,
            description: {
                pl: 'Społeczność, prawo, wybory, wolontariat i dobre maniery.',
                en: 'Community, law, elections, volunteering, and good manners.',
            },
        },
        {
            id: 'matura-pp-praca',
            sku: 'LS-MAT-WORK',
            categories: ['fiszki', 'karty-pracy'],
            exam: 'Matura podstawowa',
            title: { pl: 'Matura PP: Praca', en: 'Matura PP: Work' },
            image: 'shop/previews/matura-pp-praca.svg',
            terms: 36,
            pricePln: 12,
            priceUsd: 3,
            description: {
                pl: 'CV, etat, nadgodziny i zwolnienie — 36 haseł na maturę PP.',
                en: 'CV, employment, overtime, and sick leave — 36 terms for basic Matura.',
            },
        },
        {
            id: 'matura-pp-zdrowie',
            sku: 'LS-MAT-HEALTH',
            categories: ['fiszki', 'karty-pracy'],
            exam: 'Matura podstawowa',
            title: { pl: 'Matura PP: Zdrowie', en: 'Matura PP: Health' },
            image: 'shop/previews/matura-pp-zdrowie.svg',
            terms: 36,
            pricePln: 12,
            priceUsd: 3,
            description: {
                pl: 'Objawy, wizyta u lekarza i leczenie — 36 haseł na maturę PP.',
                en: 'Symptoms, doctor visits, and treatment — 36 terms for basic Matura.',
            },
        },
    ],
};
